// Synced from /workspace/portfolio/content/projects.draft.ts (Researcher). Edit there, then run `npm run sync:content`.
import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "nightscene",
    title: "NightScene",
    tagline: "Live crowd and wait times for bars, plus skip-the-line passes.",
    tier: "featured",
    stack: ["Expo", "React Native", "SST v3", "API Gateway WebSocket", "Lambda", "DynamoDB", "Cognito", "Zod"],
    role: "Sole owner and architect",
    period: "2025 – 2026",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "Going out means guessing which venue is worth it. Venues have no simple way to share live crowd and wait times.",
      built: [
        "Consumer app to browse and filter venues, see live counts and waits, open Uber or Lyft, and buy skip-the-line QR passes",
        "Admin app for venue owners with staff roles (super admin, bar admin, bar staff), live-ops controls, and impersonation",
        "Realtime updates pushed to both apps over WebSockets when a venue changes",
        "Apple Sign-In verified against Apple's public keys, then exchanged for Cognito tokens",
      ],
      architecture: "Two Expo apps share one SST v3 backend: HTTP and WebSocket APIs on API Gateway, Node 20 Lambdas, a single-table DynamoDB design, and Cognito with a JWT authorizer. Deploys run from GitHub Actions with keyless AWS sign-in (OIDC).",
    },
  },
  {
    slug: "fitgoai",
    title: "FitGoAI",
    tagline: "An AI coach for meals, recipes, and workouts, in English and Spanish.",
    tier: "featured",
    stack: ["Expo", "React Native", "SST", "Python", "Lambda (Docker)", "Amazon Bedrock", "OpenAI", "Google Gemini", "DynamoDB"],
    role: "Sole developer (Wenntech)",
    period: "2023 – 2024",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "Meal plans, recipes, and workouts generated for the person using the app, not pulled from a template.",
      built: [
        "Generated meal plans, recipes, and workouts, plus a health chat",
        "Ingredient analysis from photos",
        "Spanish localization, Apple sign-in, and in-app purchases",
      ],
      architecture: "Expo app on an SST backend. A Python Lambda in a Docker image wraps Bedrock, OpenAI, and Google behind one model abstraction, with separate prompt modules for meals, recipes, workouts, chat, and validation.",
    },
  },
  {
    slug: "promptlens",
    title: "promptlens",
    tagline: "See which parts of a prompt actually moved the model's answer.",
    tier: "tooling",
    stack: ["Python", "Anthropic", "OpenAI", "Bedrock", "Gemini", "Grok", "Ollama", "CLI"],
    role: "Creator",
    period: "2026",
    visibility: "public",
    repoUrl: "https://github.com/alex-wenner/prompt-lens",
    images: [],
    caseStudy: {
      problem: "There's 100x more LLM usage with 100x less visibility into why a model does what it does. This was my attempt at helping out.",
      built: [
        "Splits a prompt, tool schema, or instruction stack into features and masks them one at a time",
        "Reruns the model, scores how much the output changed, and ranks what mattered",
        "Projects the cost of an experiment before any provider calls are made",
      ],
      architecture: "Thin, optional provider adapters (Anthropic, OpenAI, GitHub Copilot, Grok, Gemini, Bedrock, Ollama, and any OpenAI-compatible endpoint) behind one interface, driven from a CLI.",
    },
  },
  {
    slug: "proofprint",
    title: "ProofPrint",
    tagline: "Signed, checkable lineage for datasets, training runs, and evals.",
    tier: "tooling",
    stack: ["Rust", "Ed25519", "Merkle log", "React", "TypeScript", "Python", "Hugging Face"],
    role: "Creator",
    period: "2026",
    visibility: "public",
    repoUrl: "https://github.com/alex-wenner/proofprint",
    images: [],
    caseStudy: {
      problem: "A signature shows who made a claim, not that it's true. ProofPrint keeps the claims and the checks on them in a log anyone can verify.",
      built: [
        "Signed records for datasets, run configs, checkpoints, scores, and third-party checks, each linking what it was built from",
        "Append-only Merkle log with recovery from interrupted writes",
        "CLI, local HTTP node, React explorer with a lineage graph, and a Python client with a Hugging Face Trainer callback",
      ],
      architecture: "Rust core, CLI, and node; files referenced by content hash; React explorer; Python recorder. Includes a nanoGPT training example.",
    },
  },
  {
    slug: "rennew",
    title: "Rennew",
    tagline: "A local-first coding-agent runtime where sessions are the unit of work.",
    tier: "tooling",
    stack: ["Python", "FastAPI", "LadybugDB", "Cypher", "React", "TypeScript", "Click"],
    role: "Creator",
    period: "2026",
    visibility: "public",
    repoUrl: "https://github.com/alex-wenner/rennew",
    images: [],
    caseStudy: {
      problem: "Treat sessions as the unit of work, so they can hand off, check each other, and share tasks, code, and memory.",
      built: [
        "Sessions that hand work to each other, validate each other, and share tasks, code, and memory",
        "The whole execution model stored as a queryable local graph",
        "Read-only Cypher queries from the CLI and web UI",
      ],
      architecture: "Python runtime with a local FastAPI server, a session-centric graph database, and a bundled React UI. Early architecture phase.",
    },
  },
  {
    slug: "works-by-sam-o",
    title: "Works by Sam Ø",
    tagline: "A site and booking platform for a creative studio that the owner edits in place.",
    tier: "client",
    stack: ["React", "Vite", "TypeScript", "SST", "Cognito"],
    role: "Built for the client",
    period: "2026",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "The studio needed a site that shows its work, books clients, and that the owner can update without a developer.",
      built: [
        "Before/after mix comparison player that switches between three projects without gaps",
        "Native consultation booking in place of a Google Calendar embed",
        "Admin mode that is the real site, with inline editing on every page",
      ],
      architecture: "React and Vite frontend deployed with SST, with Cognito handling admin sign-in.",
    },
  },
  {
    slug: "riseup",
    title: "RiseUp",
    tagline: "A prison ministry site with galleries, testimonies, and a contact form.",
    tier: "client",
    stack: ["React", "SST", "Lambda", "Cloudflare Turnstile", "GitHub Actions"],
    role: "Built the original site; later maintained by a collaborator",
    period: "2022",
    visibility: "private",
    images: [],
    liveUrl: "https://riseupprisonministry.com",
    caseStudy: {
      problem: "A prison ministry needed a home online to share its team, its story, and testimonies, and a way for people to reach out.",
      built: [
        "Landing, About Us, Testimonials, Gallery, and Contact pages with team bios and photo galleries",
        "Contact form that emails the ministry through a serverless API",
        "GitHub Actions pipeline that checks pull requests and deploys on merge to main",
      ],
      architecture: "React site deployed as a static site on AWS, with the contact form posting to API Gateway and a Lambda that sends mail through SES. Alex built the original site and pipeline in 2022. A collaborator later moved it to SST v3 and added rate limiting, input validation, and Cloudflare Turnstile anti-spam.",
    },
  },
  {
    slug: "active-towing",
    title: "Active Towing",
    tagline: "A bilingual site for a towing company.",
    tier: "client",
    stack: ["React", "TypeScript", "MUI", "SST", "Google Maps"],
    role: "Lead developer (Wenntech)",
    period: "2023",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "A Denver towing company serving English and Spanish speakers needed a site that works for both.",
      built: [
        "Bilingual home page with a language toggle, backed by a translation map for every piece of copy",
        "Service sections for towing, junk car buying, and roadside help, plus an FAQ accordion",
        "Click-to-call header, Google Maps embed, and a contact form",
      ],
      architecture: "React and TypeScript with Material UI, deployed as a static site on AWS with SST.",
    },
  },
  {
    slug: "wenntech",
    title: "Wenntech",
    tagline: "The software studio behind the client work and early products.",
    tier: "studio",
    stack: ["React", "TypeScript", "React Native", "SST", "AWS", "Python", "GitHub Actions"],
    role: "Founder",
    period: "2022 – present",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "A home for building products and sites for clients, end to end on AWS.",
      built: [
        "FitGoAI, an AI fitness and nutrition app, and client sites for RiseUp and Active Towing",
        "The wenntech.cloud site: full-screen sections, a vector wave, a full-screen menu overlay, and the black and acid-lime look this portfolio grew out of",
        "Teaching repos on building Python packages and infrastructure as code with SST",
      ],
      architecture: "Every project ships on AWS with SST from one repo, with React or React Native up front, and GitHub Actions deploying through keyless AWS sign-in (OIDC).",
    },
  },
];
