// Synced from /workspace/portfolio/content/projects.draft.ts (Researcher). Edit there, then run `npm run sync:content`.
import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "nightscene",
    title: "NightScene",
    tagline: "Live crowd and wait times for bars, plus skip-the-line passes.",
    tier: "featured",
    stack: ["Expo", "React Native", "SST v3", "API Gateway WebSocket", "Lambda", "DynamoDB", "Cognito", "Zod"],
    role: "Sole owner and architect",
    period: "2025 – 2026",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "People pick where to go out by guessing, and venues have no direct way to show how busy they are, push a deal on a slow night, or make money from the line.",
      useCase: "Someone checks live crowd and wait times, picks a spot, grabs an Uber or Lyft, and buys a skip-the-line pass. Venue staff update counts and waits from their own app and post deals that go out as push notifications.",
      approach: [
        "Two apps on one backend: a consumer app for going out and an admin app for venue owners and staff",
        "Live counts and waits pushed to every open app over WebSockets the moment staff change them",
        "Paid skip-the-line QR passes and venue deals as the revenue side",
        "Staff roles (super admin, bar admin, bar staff) so each venue controls who can change what",
      ],
      status: { state: "active", note: "In active development with installable builds through TestFlight." },
    },
  },
  {
    slug: "fitgoai",
    title: "FitGoAI",
    tagline: "An AI coach for meals, recipes, and workouts, in English and Spanish.",
    tier: "featured",
    stack: ["Expo", "React Native", "SST", "Python", "Lambda (Docker)", "Amazon Bedrock", "OpenAI", "Google Gemini", "DynamoDB"],
    role: "Sole developer (Wenntech)",
    period: "2023 – 2024",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "Personalized meal and training plans usually mean paying a coach, and most fitness apps hand out the same templates to everyone, mostly in English only.",
      useCase: "A user tells the app their goals, gets meal plans, recipes, and workouts built for them, asks follow-up questions in a health chat, and snaps a photo to check what's in their food, in English or Spanish.",
      approach: [
        "Generated meal plans, recipes, workouts, and a health chat, each with its own prompt",
        "One model layer over Bedrock, OpenAI, and Google, so providers can be swapped on cost or quality",
        "Ingredient analysis from photos",
        "Spanish localization, Apple sign-in, and in-app purchases for a paid tier",
      ],
      status: { state: "archived", note: "Built through a pre-release in early 2024 under Wenntech." },
    },
  },
  {
    slug: "promptlens",
    title: "promptlens",
    tagline: "See which parts of a prompt actually moved the model's answer.",
    tier: "tooling",
    stack: ["Python", "Anthropic", "OpenAI", "Bedrock", "Gemini", "Grok", "Ollama", "CLI"],
    role: "Creator",
    period: "2026",
    visibility: "public",
    repoUrl: "https://github.com/alex-wenner/prompt-lens",
    images: [],
    caseStudy: {
      problem: "Teams ship LLM features with no idea which part of a prompt is actually driving the output. There's 100x more usage with 100x less visibility, so debugging a bad answer or a wrong tool call is guesswork, and so is the bill.",
      useCase: "An engineer whose agent keeps picking the wrong tool runs promptlens to see which instruction or tool description is steering it, after checking what the experiment will cost before making any calls.",
      approach: [
        "Splits a prompt, tool schema, or instruction stack into features and masks them one at a time",
        "Reruns the model, scores how much the output changed, and ranks what mattered",
        "Projects the cost of an experiment up front",
        "Thin adapters for Anthropic, OpenAI, Copilot, Grok, Gemini, Bedrock, and local models through Ollama",
      ],
      status: { state: "active", note: "Public on GitHub, used through a CLI, and the most-starred of these repos." },
    },
  },
  {
    slug: "proofprint",
    title: "ProofPrint",
    tagline: "Infrastructure for AI labs to regulate themselves, with proof instead of PDFs.",
    tier: "tooling",
    stack: ["Rust", "Ed25519", "Merkle log", "React", "TypeScript", "Python", "Hugging Face"],
    role: "Creator",
    period: "2026",
    visibility: "public",
    repoUrl: "https://github.com/alex-wenner/proofprint",
    images: [],
    caseStudy: {
      problem: "AI labs are being asked to regulate themselves, and right now that means a \"responsible scaling\" PDF and a request to be trusted. There's no way for anyone outside to check what a lab actually trained or whether its evals hold up.",
      useCase: "A lab publishes a signed record of each training run and eval while keeping its weights and data private. A rival lab or auditor re-runs the eval and signs what they found. The hash chain does the talking, so self-regulation is checkable without a regulator stepping in.",
      approach: [
        "Every dataset, run, checkpoint, and eval becomes a signed record that links to what it was built from",
        "Files are referenced by hash, so config, losses, eval results, and the hashes that pin them can be published while weights and data stay proprietary",
        "Records go into an append-only log with proofs, so history can't be quietly rewritten",
        "Drops into existing training with four Python calls or a Hugging Face Trainer callback",
      ],
      status: { state: "early", note: "Works end to end on one machine with a CLI, local node, and explorer. Next is a real fine-tune, third-party eval re-runs, and independently witnessed logs." },
    },
  },
  {
    slug: "rennew",
    title: "Rennew",
    tagline: "A local-first coding-agent runtime where sessions are the unit of work.",
    tier: "tooling",
    stack: ["Python", "FastAPI", "LadybugDB", "Cypher", "React", "TypeScript", "Click"],
    role: "Creator",
    period: "2026",
    visibility: "public",
    repoUrl: "https://github.com/alex-wenner/rennew",
    images: [],
    caseStudy: {
      problem: "Coding agents work in isolated sessions. Once several are working the same codebase, handoffs, reviews, and shared context get lost, and there's no record of who did what.",
      useCase: "A developer runs several agent sessions, hands a task from one to another, has a second session validate the work, and queries the history to see exactly what happened.",
      approach: [
        "Sessions are the unit of work and can hand off to, validate, and overlap with each other",
        "Tasks, code, memory, and artifacts are stored as one local graph that can be queried",
        "Runs locally with a FastAPI server, a React UI, and a CLI",
      ],
      status: { state: "early", note: "Initial architecture. The graph, server, UI, and first handoff primitives are in place." },
    },
  },
  {
    slug: "works-by-sam-o",
    title: "Works by Sam Ø",
    tagline: "A site and booking platform for a creative studio that the owner edits in place.",
    tier: "client",
    stack: ["React", "Vite", "TypeScript", "SST", "Cognito"],
    role: "Built for the client",
    period: "2026",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "A creative studio needs to show its work, book clients, and keep the site current without paying a developer for every change.",
      useCase: "A prospective client compares before and after mixes, then books a consultation on the site. The owner signs in and edits any page in place.",
      approach: [
        "A before/after mix player that switches between three projects without gaps",
        "Native consultation booking in place of a calendar embed",
        "An admin mode that is the real site, with inline editing on every page",
      ],
      status: { state: "active", note: "In development. Content is still being approved before launch." },
    },
  },
  {
    slug: "riseup",
    title: "RiseUp",
    tagline: "A prison ministry site with galleries, testimonies, and a contact form.",
    tier: "client",
    stack: ["React", "SST", "Lambda", "Cloudflare Turnstile", "GitHub Actions"],
    role: "Built the original site; later maintained by a collaborator",
    period: "2022",
    visibility: "private",
    images: [],
    liveUrl: "https://riseupprisonministry.com",
    caseStudy: {
      problem: "A small prison ministry needed a credible place online to tell its story and let people reach out or give, without anyone there managing servers.",
      useCase: "A visitor reads about the team and testimonies, browses photos, donates, or sends a message that lands in the ministry's inbox.",
      approach: [
        "Pages for the team, testimonies, gallery, and contact",
        "A contact form that emails the ministry through a serverless function",
        "A pipeline that checks pull requests and deploys on merge",
      ],
      status: { state: "live", note: "Live at riseupprisonministry.com. A collaborator has since moved it to SST v3 and added anti-spam protection." },
    },
  },
  {
    slug: "active-towing",
    title: "Active Towing",
    tagline: "A bilingual site for a towing company.",
    tier: "client",
    stack: ["React", "TypeScript", "MUI", "SST", "Google Maps"],
    role: "Lead developer (Wenntech)",
    period: "2023",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "A Denver towing company with many Spanish-speaking customers needed people to find it and call fast, in either language.",
      useCase: "A stranded driver lands on the site, switches to Spanish if they want, sees the services, and taps to call.",
      approach: [
        "Every piece of copy in English and Spanish behind one toggle",
        "Service sections for towing, junk car buying, and roadside help, plus an FAQ",
        "Click-to-call, a map, and a contact form",
      ],
      status: { state: "archived", note: "Built in 2023 under Wenntech." },
    },
  },
  {
    slug: "wenntech",
    title: "Wenntech",
    tagline: "The software studio behind the client work and early products.",
    tier: "studio",
    stack: ["React", "TypeScript", "React Native", "SST", "AWS", "Python", "GitHub Actions"],
    role: "Founder",
    period: "2022 – present",
    visibility: "private",
    images: [],
    caseStudy: {
      problem: "Small businesses and early products need real apps and sites built and run on AWS, without hiring a full team.",
      useCase: "A client brings an idea, and Wenntech designs, builds, and deploys it on AWS, from marketing sites to AI-backed mobile apps.",
      approach: [
        "FitGoAI, plus client sites for RiseUp and Active Towing",
        "Every project ships on AWS with SST, with React or React Native on the front",
        "GitHub Actions deploys through keyless AWS sign-in",
        "Teaching repos on Python packaging and infrastructure as code",
      ],
      status: { state: "active", note: "Alex's studio since 2022." },
    },
  },
];
